FROM ubuntu:18.04

ARG USER=docker
ARG UID=1000
ARG GID=1000
ARG PW=docker
ARG HOME='/Users/jeremy'

RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y sudo && \
    mkdir -p ${HOME} && useradd -m ${USER} --uid=${UID} -d /Users/jeremy -G sudo && echo "${USER}:${PW}" | chpasswd

RUN apt-get -y install git ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip && \
    cd /tmp && git clone https://github.com/neovim/neovim && cd neovim && make && make install && cd / && rm -rf /tmp/*

USER ${UID}:${GID}
WORKDIR /${HOME}
